server:
  port: 8200

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot-chat
          group: comments-chat
          content-type: application/json
        newComments:
          destination: learning-spring-boot-chat
          group: comments-chat
          content-type: application/json
        clientToBroker:
          destination: learning-spring-boot-chat-user-messages
          group: app-chatMessages
        brokerToClient:
          destination: learning-spring-boot-chat-user-messages
          group: topic-chatMessages
  data:
    mongodb:
      host: 218.38.15.93
      port: 27017
  rabbitmq:
    host: 218.38.15.73
    port: 30672 
